/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ModelResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-01T16:43:08.765604+02:00[Europe/Paris]")
public class ModelResponse {
  public static final String SERIALIZED_NAME_MODEL_PATH = "modelPath";
  @SerializedName(SERIALIZED_NAME_MODEL_PATH)
  private String modelPath;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PREDICTION = "prediction";
  @SerializedName(SERIALIZED_NAME_PREDICTION)
  private String prediction;

  public static final String SERIALIZED_NAME_PROBABILITIES = "probabilities";
  @SerializedName(SERIALIZED_NAME_PROBABILITIES)
  private Map<String, String> probabilities = null;


  public ModelResponse modelPath(String modelPath) {
    
    this.modelPath = modelPath;
    return this;
  }

   /**
   * Get modelPath
   * @return modelPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModelPath() {
    return modelPath;
  }


  public void setModelPath(String modelPath) {
    this.modelPath = modelPath;
  }


  public ModelResponse id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ModelResponse prediction(String prediction) {
    
    this.prediction = prediction;
    return this;
  }

   /**
   * Get prediction
   * @return prediction
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPrediction() {
    return prediction;
  }


  public void setPrediction(String prediction) {
    this.prediction = prediction;
  }


  public ModelResponse probabilities(Map<String, String> probabilities) {
    
    this.probabilities = probabilities;
    return this;
  }

  public ModelResponse putProbabilitiesItem(String key, String probabilitiesItem) {
    if (this.probabilities == null) {
      this.probabilities = new HashMap<String, String>();
    }
    this.probabilities.put(key, probabilitiesItem);
    return this;
  }

   /**
   * Get probabilities
   * @return probabilities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getProbabilities() {
    return probabilities;
  }


  public void setProbabilities(Map<String, String> probabilities) {
    this.probabilities = probabilities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelResponse modelResponse = (ModelResponse) o;
    return Objects.equals(this.modelPath, modelResponse.modelPath) &&
        Objects.equals(this.id, modelResponse.id) &&
        Objects.equals(this.prediction, modelResponse.prediction) &&
        Objects.equals(this.probabilities, modelResponse.probabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelPath, id, prediction, probabilities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelResponse {\n");
    sb.append("    modelPath: ").append(toIndentedString(modelPath)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    prediction: ").append(toIndentedString(prediction)).append("\n");
    sb.append("    probabilities: ").append(toIndentedString(probabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

