/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModelResponse
 */
public class ModelResponseTest {
    private final ModelResponse model = new ModelResponse();

    /**
     * Model tests for ModelResponse
     */
    @Test
    public void testModelResponse() {
        // TODO: test ModelResponse
    }

    /**
     * Test the property 'modelPath'
     */
    @Test
    public void modelPathTest() {
        // TODO: test modelPath
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'prediction'
     */
    @Test
    public void predictionTest() {
        // TODO: test prediction
    }

}
