/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ModelSpecification;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutomationApiV10PredictionAdminApi
 */
@Ignore
public class AutomationApiV10PredictionAdminApiTest {

    private final AutomationApiV10PredictionAdminApi api = new AutomationApiV10PredictionAdminApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHeartBeatTest() throws ApiException {
        api.getHeartBeat();

        // TODO: test validations
    }
    
    /**
     * Returns the list of ML models
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getModelTest() throws ApiException {
        api.getModel();

        // TODO: test validations
    }
    
    /**
     * Add a model
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postModelTest() throws ApiException {
        ModelSpecification payload = null;
        api.postModel(payload);

        // TODO: test validations
    }
    
}
